🧹 Data Cleaning & Preprocessing
🎯 Objective:
Learn how to clean, preprocess, and prepare data before applying Machine Learning models.

⚠️ Why this matters?
Garbage Data ❌ → Garbage Output ❌
Clean Data ✅ → Better Models ✅

In [1]:
import pandas as pd
import numpy as np

🔹 What is Data Cleaning?
Data Cleaning is the process of:

Fixing incorrect data
Handling missing values
Removing duplicates
Standardizing formats
🔹 Why is Data Preprocessing Important?
Machine Learning models:

Cannot handle missing or messy data properly
Require numerical and consistent input
🔹 Example of Messy Data:
Name	Age	City
Ram	25	Mumbai
Shyam	NaN	mumbai
Ram	25	Mumbai
Problems:

Missing values
Inconsistent text
Duplicate rows

In [2]:
data = {
    "Name": ["Ram", "Shyam", "Ram", "Sita", None,"Shyam","Shyam","Shyam","Ram"],
    "Age": [25, np.nan, 25, 30, 22,13,17,18,19],
    "City": ["Mumbai", "mumbai", "Mumbai", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi", "Delhi"]
}
print(data)
df = pd.DataFrame(data)
df

{'Name': ['Ram', 'Shyam', 'Ram', 'Sita', None, 'Shyam', 'Shyam', 'Shyam', 'Ram'], 'Age': [25, nan, 25, 30, 22, 13, 17, 18, 19], 'City': ['Mumbai', 'mumbai', 'Mumbai', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi', 'Delhi']}

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

🔹 Common Data Issues
Missing Values → NaN
Duplicate Records
Incorrect Data Types
Inconsistent Text (Mumbai vs mumbai)
We must identify and fix these issues before using data.

In [3]:
# First few rows
print(df.head())

# Data info
df.info()

# Summary statistics
df.describe()

    Name   Age    City
0    Ram  25.0  Mumbai
1  Shyam   NaN  mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
4   None  22.0   Delhi
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    8 non-null      object
 1   Age     8 non-null      float64
 2   City    9 non-null      object
dtypes: float64(1), object(2)
memory usage: 348.0+ bytes

            Age
count   8.00000
mean   21.12500
std     5.43632
min    13.00000
25%    17.75000
50%    20.50000
75%    25.00000
max    30.00000

🔹 Missing Values
Missing values are represented as:

NaN (Not a Number)
None
🔍 Steps:
Identify missing values
Count them
Decide:
Drop
Fill

In [4]:
# Check missing values
df.isnull()

# Count missing values
df.isnull().sum()

Name    1
Age     1
City    0
dtype: int64

In [5]:
# Drop rows with missing values
df_drop = df.dropna()
df_drop

    Name   Age    City
0    Ram  25.0  Mumbai
2    Ram  25.0  Mumbai
3   Sita  30.0   Delhi
5  Shyam  13.0   Delhi
6  Shyam  17.0   Delhi
7  Shyam  18.0   Delhi
8    Ram  19.0   Delhi

🔹 Filling Missing Values
Numerical Columns:
Mean
Median
Categorical Columns:
Mode
🧠 When to Use:
Mean → Normal data
Median → Skewed data
Mode → Categories

In [6]:
# ✅ Best Practice

df["Age"] = df["Age"].fillna(df["Age"].mean())
df["Name"] = df["Name"].fillna(df["Name"].mode()[0])


df

    Name     Age    City
0    Ram  25.000  Mumbai
1  Shyam  21.125  mumbai
2    Ram  25.000  Mumbai
3   Sita  30.000   Delhi
4  Shyam  22.000   Delhi
5  Shyam  13.000   Delhi
6  Shyam  17.000   Delhi
7  Shyam  18.000   Delhi
8    Ram  19.000   Delhi

🔹 Selecting Multiple Columns
To work on multiple columns together:

✅ Syntax:
df[["col1", "col2"]]

🔹 Why use this?
Apply same operation on multiple columns
Clean multiple columns at once
Save time and avoid repetition

In [7]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "Age": [20, np.nan, 25, 30,20],
    "Salary": [20000, 25000, np.nan, 40000,20000],
    "City": ["Nashik", "Delhi", "Pune", "Akola","Mumbai"]
})

df

    Age   Salary    City
0  20.0  20000.0  Nashik
1   NaN  25000.0   Delhi
2  25.0      NaN    Pune
3  30.0  40000.0   Akola
4  20.0  20000.0  Mumbai

In [8]:
# Fill multiple columns with mean

df[["Age", "Salary"]] = df[["Age", "Salary"]].fillna(df[["Age", "Salary"]].mean())

df

     Age   Salary    City
0  20.00  20000.0  Nashik
1  23.75  25000.0   Delhi
2  25.00  26250.0    Pune
3  30.00  40000.0   Akola
4  20.00  20000.0  Mumbai

In [9]:
# Convert multiple columns to integer

df[["Age", "Salary"]] = df[["Age", "Salary"]].astype(int)

df.dtypes
df

   Age  Salary    City
0   20   20000  Nashik
1   23   25000   Delhi
2   25   26250    Pune
3   30   40000   Akola
4   20   20000  Mumbai

In [10]:
# Increase values by 10%

df[["Age", "Salary"]] = df[["Age", "Salary"]].apply(lambda x: x * 1.1)

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [11]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0  Mumbai

In [12]:
# Replace specific values

df[["City"]] = df[["City"]].replace("Mumbai", "Pune")

df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [13]:
df

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

🔹 Encoding (Categorical → Numerical)
Machine Learning models only understand numbers.

Types of Data:
Nominal → No order (City, Color)
Ordinal → Ordered (Low, Medium, High)
Methods:
One-Hot Encoding
Label Encoding

In [14]:
df_encoded = pd.get_dummies(df, columns=["City"])
df_encoded

    Age   Salary  City_Akola  City_Delhi  City_Nashik  City_Pune
0  22.0  22000.0       False       False         True      False
1  25.3  27500.0       False        True        False      False
2  27.5  28875.0       False       False        False       True
3  33.0  44000.0        True       False        False      False
4  22.0  22000.0       False       False        False       True

🔹 Label Encoding (Concept)
Converts categories into numbers:

Example: Mumbai → 0
Delhi → 1

⚠️ Not ideal for nominal data (creates fake order)

🔹 Duplicate Records
Duplicate data can:

Bias model
Reduce accuracy
Solution:
Use drop_duplicates()

In [15]:
df_no_dup = df.drop_duplicates()
df_no_dup

    Age   Salary    City
0  22.0  22000.0  Nashik
1  25.3  27500.0   Delhi
2  27.5  28875.0    Pune
3  33.0  44000.0   Akola
4  22.0  22000.0    Pune

In [16]:
# Convert all city names to lowercase
df["City"] = df["City"].str.upper()
df2=df.dropna()
#FEMALE female Female FeMale
df2

    Age   Salary    City
0  22.0  22000.0  NASHIK
1  25.3  27500.0   DELHI
2  27.5  28875.0    PUNE
3  33.0  44000.0   AKOLA
4  22.0  22000.0    PUNE

In [17]:
df2.dropna()
df2["Age"] = df2["Age"].astype(int)
df2

   Age   Salary    City
0   22  22000.0  NASHIK
1   25  27500.0   DELHI
2   27  28875.0    PUNE
3   33  44000.0   AKOLA
4   22  22000.0    PUNE

🌧️ Rainfall Dataset Cleaning
🎯 Objective:
Clean and preprocess the dataset rainfall.csv

🔹 Dataset Columns:
date
rainfall
temperature
humidity
wind_speed
weather_condition
⚠️ Possible Issues:
Date format not parsed
Missing values (if any)
Inconsistent text (Rainy / rainy)
Wrong data types
Outliers
✅ Steps We Will Perform:
Load dataset
Convert date column
Handle missing values
Fix text inconsistencies
Remove duplicates
Detect & handle outliers
Final clean dataset

📤 Upload CSV File from Local System (Google Colab)
Since the file is on your computer, we need to upload it manually.

🔹 Steps:
Run the cell below
Click "Choose Files"
Select rainfall.csv
File will be uploaded to Colab environment
After uploading, we can load it using pandas.

In [27]:
from google.colab import files

uploaded = files.upload()

Saving rainfall.csv to rainfall.csv

In [28]:
# Check uploaded file name
file_name = list(uploaded.keys())[0]
print("Uploaded file:", file_name)

Uploaded file: rainfall.csv

In [29]:
import pandas as pd

# Load the uploaded file
df = pd.read_csv(file_name)

df.head()

          Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

🔧 Data Cleaning Operations on rainfall.csv
After uploading and loading the dataset, we perform:

✅ Operations:
Inspect data
Convert date column
Handle missing values
Fix text inconsistencies
Remove duplicates
Handle outliers
Feature engineering
Encoding categorical data
Save cleaned dataset
Each step is important for ML readiness.

## 🔧 Data Cleaning Operations on rainfall.csv

After uploading and loading the dataset, we perform:

---

### ✅ Operations:
1. Inspect data
2. Convert date column
3. Handle missing values
4. Fix text inconsistencies
5. Remove duplicates
6. Handle outliers
7. Feature engineering
8. Encoding categorical data
9. Save cleaned dataset

---

Each step is important for ML readiness.

In [30]:
df.head()

df.info()

df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0    Area                          6727 non-null   object
 1   Year                           6727 non-null   int64
 2   average_rain_fall_mm_per_year  5953 non-null   object
dtypes: int64(1), object(2)
memory usage: 157.8+ KB

 Area                              0
Year                               0
average_rain_fall_mm_per_year    774
dtype: int64

🔹 Convert Date Column
Convert string → datetime format

Helps in:

Sorting
Time-based analysis

In [33]:
print(df.columns.tolist())

[' Area', 'Year', 'average_rain_fall_mm_per_year']

In [34]:
import pandas as pd

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Clean Year column
df["Year"] = df["Year"].astype(str).str.strip()

# Convert Year to numeric
df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6727 entries, 0 to 6726
Data columns (total 3 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Area                           6727 non-null   object
 1   Year                           6727 non-null   int64
 2   average_rain_fall_mm_per_year  5953 non-null   object
dtypes: int64(1), object(2)
memory usage: 157.8+ KB

In [35]:
df.columns = df.columns.str.strip()

🔹 Handle Missing Values
Numerical Columns:
rainfall
temperature
humidity
wind_speed
➡️ Fill with mean

Categorical:
weather_condition
➡️ Fill with mode

In [37]:
import pandas as pd

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['Area', 'Year', 'average_rain_fall_mm_per_year']

In [40]:
print(df[num_cols].dtypes)

Area                             object
Year                              int64
average_rain_fall_mm_per_year    object
dtype: object

In [41]:
num_cols = ["Area", "Year", "average_rain_fall_mm_per_year"]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [42]:
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

In [43]:
print(df.isnull().sum())

Area                             6727
Year                                0
average_rain_fall_mm_per_year       0
dtype: int64

In [44]:
import pandas as pd

# Numerical columns
num_cols = ["Area", "Year", "average_rain_fall_mm_per_year"]

# Convert columns to numeric
for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Fill missing numerical values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Check missing values
print(df.isnull().sum())

Area                             6727
Year                                0
average_rain_fall_mm_per_year       0
dtype: int64

🔹 Fix Text Inconsistency
Standardize text:

Rainy → rainy
SUNNY → sunny

In [46]:
import pandas as pd

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# Convert numerical columns to numeric
num_cols = ["Area", "Year", "average_rain_fall_mm_per_year"]

for col in num_cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Fill missing numerical values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Convert Area to lowercase
df["Area"] = df["Area"].astype(str).str.lower().str.strip()

# Check missing values
print(df.isnull().sum())

# Show unique areas
print(df["Area"].unique())

# Display first 5 rows
print(df.head())

Area                             0
Year                             0
average_rain_fall_mm_per_year    0
dtype: int64
['nan']
  Area  Year  average_rain_fall_mm_per_year
0  nan  1985                          327.0
1  nan  1986                          327.0
2  nan  1987                          327.0
3  nan  1989                          327.0
4  nan  1990                          327.0

In [47]:
df.to_csv("cleaned_rainfall.csv", index=False)

# Download
files.download("cleaned_rainfall.csv")

In [48]:
import pandas as pd
from google.colab import files

# Convert to Excel
df.to_excel("cleaned_rainfall.xlsx", index=False)

# Download
files.download("cleaned_rainfall.xlsx")

🎓 Student Performance Dataset – Data Cleaning
🎯 Objective:
Clean and preprocess student dataset for ML

🔹 Columns:
name
age
gender
marks
attendance
city
⚠️ Possible Issues:
Missing values
Inconsistent text (Male / male)
Invalid marks (>100 or <0)
Duplicates

In [49]:
import pandas as pd
import numpy as np

data = {
    "name": ["Amit", "Sara", "John", "Amit", None],
    "age": [20, 21, np.nan, 20, 19],
    "gender": ["Male", "female", "Male", "Male", "FEMALE"],
    "marks": [85, 90, 105, 85, -5],
    "attendance": [90, 85, 80, 90, None],
    "city": ["Mumbai", "Delhi", "mumbai", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)
df

   name   age  gender  marks  attendance    city
0  Amit  20.0    Male     85        90.0  Mumbai
1  Sara  21.0  female     90        85.0   Delhi
2  John   NaN    Male    105        80.0  mumbai
3  Amit  20.0    Male     85        90.0  Mumbai
4  None  19.0  FEMALE     -5         NaN    Pune

In [50]:
df.info()
df.isnull().sum()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        4 non-null      object
 1   age         4 non-null      float64
 2   gender      5 non-null      object
 3   marks       5 non-null      int64
 4   attendance  4 non-null      float64
 5   city        5 non-null      object
dtypes: float64(2), int64(1), object(3)
memory usage: 372.0+ bytes

             age       marks  attendance
count   4.000000    5.000000    4.000000
mean   20.000000   72.000000   86.250000
std     0.816497   43.817805    4.787136
min    19.000000   -5.000000   80.000000
25%    19.750000   85.000000   83.750000
50%    20.000000   85.000000   87.500000
75%    20.250000   90.000000   90.000000
max    21.000000  105.000000   90.000000

🔹 Handling Missing Values
age → mean
attendance → mean
name → "Unknown"

In [51]:
df["age"].fillna(df["age"].mean(), inplace=True)
df["attendance"].fillna(df["attendance"].mean(), inplace=True)
df["name"].fillna("Unknown", inplace=True)

df

/tmp/ipykernel_8214/1440735091.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["age"].fillna(df["age"].mean(), inplace=True)
/tmp/ipykernel_8214/1440735091.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["attendance"].fillna(df["attendance"].mean(), inplace=True)
/tmp/ipykernel_8214/1440735091.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace=True)

      name   age  gender  marks  attendance    city
0     Amit  20.0    Male     85       90.00  Mumbai
1     Sara  21.0  female     90       85.00   Delhi
2     John  20.0    Male    105       80.00  mumbai
3     Amit  20.0    Male     85       90.00  Mumbai
4  Unknown  19.0  FEMALE     -5       86.25    Pune

In [52]:
df["gender"] = df["gender"].str.lower()
df["city"] = df["city"].str.lower()

df

      name   age  gender  marks  attendance    city
0     Amit  20.0    male     85       90.00  mumbai
1     Sara  21.0  female     90       85.00   delhi
2     John  20.0    male    105       80.00  mumbai
3     Amit  20.0    male     85       90.00  mumbai
4  Unknown  19.0  female     -5       86.25    pune

🔹 Fix Invalid Data
Marks should be:

Between 0 and 100

In [53]:
df = df[(df["marks"] >= 0) & (df["marks"] <= 100)]

df

   name   age  gender  marks  attendance    city
0  Amit  20.0    male     85        90.0  mumbai
1  Sara  21.0  female     90        85.0   delhi
3  Amit  20.0    male     85        90.0  mumbai

🔹 Basic Questions
Load a CSV file and display:

First 5 rows
Last 5 rows
Find:

Total number of rows & columns
Data types of each column
Identify missing values:

Which columns have missing values?
Count them
Fill missing values:

Numerical → mean
Categorical → mode
Remove duplicate rows

Convert a column:

"date" → datetime format
Rename columns:

Change column names to lowercase
Change data type:

Convert float → int (where applicable)

1. Load CSV file

In [61]:
df = pd.read_csv("rainfall.csv")

# Remove extra spaces from column names
df.columns = df.columns.str.strip()

# First 5 rows
print("First 5 rows:")
print(df.head())

# Last 5 rows
print("\nLast 5 rows:")
print(df.tail())

First 5 rows:
          Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

Last 5 rows:
          Area  Year average_rain_fall_mm_per_year
6722  Zimbabwe  2013                           657
6723  Zimbabwe  2014                           657
6724  Zimbabwe  2015                           657
6725  Zimbabwe  2016                           657
6726  Zimbabwe  2017                           657

2. Total rows, columns, data types

In [62]:
print("\nShape of DataFrame:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nData Types:")
print(df.dtypes)

Shape of DataFrame:
Rows: 6727
Columns: 3

Data Types:
Area                             object
Year                              int64
average_rain_fall_mm_per_year    object
dtype: object

3. Identify missing values

In [63]:
print("\nMissing values in each column:")
print(df.isnull().sum())

print("\nColumns having missing values:")
print(df.columns[df.isnull().any()])

Missing values in each column:
Area                               0
Year                               0
average_rain_fall_mm_per_year    774
dtype: int64

Columns having missing values:
Index(['average_rain_fall_mm_per_year'], dtype='object')

4. Fill missing values

In [64]:
# Numerical columns
num_cols = df.select_dtypes(include="number").columns

# Fill numerical missing values with mean
df[num_cols] = df[num_cols].fillna(df[num_cols].mean())

# Categorical columns
cat_cols = df.select_dtypes(include="object").columns

# Fill categorical missing values with mode
for col in cat_cols:
    if df[col].isnull().any():
        df[col] = df[col].fillna(df[col].mode()[0])

5. Remove duplicate rows

In [65]:
df = df.drop_duplicates()

print("\nDuplicates removed.")
print("Rows after removing duplicates:", len(df))

Duplicates removed.
Rows after removing duplicates: 6727

6. Convert date column to datetime

In [66]:
# Your dataset does NOT have a date column.
# It has a Year column instead.

df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

print("\nYear data type:")
print(df["Year"].dtype)

Year data type:
int64

7. Rename columns to lowercase

In [67]:
df.columns = df.columns.str.lower()

print("\nColumn names after converting to lowercase:")
print(df.columns.tolist())

Column names after converting to lowercase:
['area', 'year', 'average_rain_fall_mm_per_year']

8. Convert float to int where applicable

In [68]:
# Rainfall is a measurement, so normally we should NOT
# convert it to int because decimals can be meaningful.

# Example: If you specifically want Year as integer:
df["year"] = df["year"].astype("Int64")

print("\nFinal data types:")
print(df.dtypes)

Final data types:
area                             object
year                              Int64
average_rain_fall_mm_per_year    object
dtype: object

9. Final dataframe

In [69]:
print("\nFinal DataFrame:")
print(df.head())

Final DataFrame:
          area  year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

## 🔹 Intermediate Questions

1. Select multiple columns and:
   - Fill missing values together

2. Apply transformation:
   - Increase salary/marks by 10%

3. Fix inconsistent text:
   - "Mumbai", "mumbai", "MUMBAI" → one format

4. Create new column:
   - Example: "Pass/Fail" based on marks

5. Filter data:
   - Students with marks > 80
   - Rainfall > 10

6. Drop unnecessary columns:
   - Based on relevance

7. Apply One-Hot Encoding:
   - On categorical columns

8. Sort dataset:
   - Based on date or marks

In [74]:
import pandas as pd

# Load CSV file
df = pd.read_csv("rainfall.csv")

# Clean column names
df.columns = df.columns.str.strip()

print("Original Data:")
print(df.head())


# ============================================
# 1. Select multiple columns and fill missing values
# ============================================

cols = ["Year", "average_rain_fall_mm_per_year"]

# Convert to numeric
for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Fill missing values with mean
df[cols] = df[cols].fillna(df[cols].mean())

print("\nAfter filling missing values:")
print(df.isnull().sum())


# ============================================
# 2. Apply transformation - Increase rainfall by 10%
# ============================================

df["average_rain_fall_mm_per_year"] = (
    df["average_rain_fall_mm_per_year"] * 1.10
)

print("\nAfter increasing rainfall by 10%:")
print(df.head())


# ============================================
# 3. Fix inconsistent text
# ============================================

# Convert Area names to lowercase and remove spaces
df["Area"] = df["Area"].astype(str).str.strip().str.lower()

print("\nUnique Area names:")
print(df["Area"].unique())


# ============================================
# 4. Create a new column
# ============================================

# Create rainfall category
df["Rainfall_Category"] = df["average_rain_fall_mm_per_year"].apply(
    lambda x: "High" if x > 1000 else "Low"
)

print("\nRainfall Category:")
print(df[["Area", "average_rain_fall_mm_per_year", "Rainfall_Category"]].head())


# ============================================
# 5. Filter data - Rainfall > 10
# ============================================

high_rainfall = df[
    df["average_rain_fall_mm_per_year"] > 10
]

print("\nAreas with rainfall greater than 10:")
print(high_rainfall)


# ============================================
# 6. Drop unnecessary columns
# ============================================

# Example: Remove Year if it is not required
df = df.drop("Year", axis=1)

print("\nAfter dropping Year:")
print(df.head())


# ============================================
# 7. One-Hot Encoding
# ============================================

df = pd.get_dummies(df, columns=["Area"])

print("\nAfter One-Hot Encoding:")
print(df.head())


# ============================================
# 8. Sort dataset
# ============================================

df = df.sort_values(
    "average_rain_fall_mm_per_year",
    ascending=False
)

print("\nSorted by rainfall (highest first):")
print(df.head())

Original Data:
          Area  Year average_rain_fall_mm_per_year
0  Afghanistan  1985                           327
1  Afghanistan  1986                           327
2  Afghanistan  1987                           327
3  Afghanistan  1989                           327
4  Afghanistan  1990                           327

After filling missing values:
Area                             0
Year                             0
average_rain_fall_mm_per_year    0
dtype: int64

After increasing rainfall by 10%:
          Area  Year  average_rain_fall_mm_per_year
0  Afghanistan  1985                          359.7
1  Afghanistan  1986                          359.7
2  Afghanistan  1987                          359.7
3  Afghanistan  1989                          359.7
4  Afghanistan  1990                          359.7

Unique Area names:
['afghanistan' 'albania' 'algeria' 'american samoa' 'andorra' 'angola'
 'antigua and barbuda' 'argentina' 'armenia' 'aruba' 'australia' 'austria'
 'azerbaijan' 'bahamas' 'bahrain' 'bangladesh' 'barbados' 'belarus'
 'belgium' 'belize' 'benin' 'bermuda' 'bhutan' 'bolivia'
 'bosnia and herzegovina' 'botswana' 'brazil' 'british virgin islands'
 'brunei darussalam' 'bulgaria' 'burkina faso' 'burundi' 'cabo verde'
 'cambodia' 'cameroon' 'canada' 'cayman islands'
 'central african republic' 'chad' 'channel islands' 'chile' 'china'
 'colombia' 'comoros' 'congo, dem. rep.' 'congo, rep.' 'costa rica'
 "cote d'ivoire" 'croatia' 'cuba' 'curacao' 'cyprus' 'czech republic'
 'denmark' 'djibouti' 'dominica' 'dominican republic' 'ecuador' 'egypt'
 'el salvador' 'equatorial guinea' 'eritrea' 'estonia' 'eswatini'
 'ethiopia' 'faroe islands' 'fiji' 'finland' 'france' 'french polynesia'
 'gabon' 'gambia' 'georgia' 'germany' 'ghana' 'gibraltar' 'greece'
 'greenland' 'grenada' 'guam' 'guatemala' 'guinea' 'guinea-bissau'
 'guyana' 'haiti' 'honduras' 'hong kong sar, china' 'hungary' 'iceland'
 'india' 'indonesia' 'iran' 'iraq' 'ireland' 'isle of man' 'israel'
 'italy' 'jamaica' 'japan' 'jordan' 'kazakhstan' 'kenya' 'kiribati'
 'north korea' 'south korea' 'kosovo' 'kuwait' 'kyrgyz republic' 'lao pdr'
 'latvia' 'lebanon' 'lesotho' 'liberia' 'libya' 'liechtenstein'
 'lithuania' 'luxembourg' 'macao sar, china' 'macedonia' 'madagascar'
 'malawi' 'malaysia' 'maldives' 'mali' 'malta' 'marshall islands'
 'mauritania' 'mauritius' 'mexico' 'micronesia' 'moldova' 'monaco'
 'mongolia' 'montenegro' 'morocco' 'mozambique' 'myanmar' 'namibia'
 'nauru' 'nepal' 'netherlands' 'new caledonia' 'new zealand' 'nicaragua'
 'niger' 'nigeria' 'northern mariana islands' 'norway' 'oman' 'pakistan'
 'palau' 'panama' 'papua new guinea' 'paraguay' 'peru' 'philippines'
 'poland' 'portugal' 'puerto rico' 'qatar' 'romania' 'russia' 'rwanda'
 'samoa' 'san marino' 'sao tome and principe' 'saudi arabia' 'senegal'
 'serbia' 'seychelles' 'sierra leone' 'singapore'
 'sint maarten (dutch part)' 'slovak republic' 'slovenia'
 'solomon islands' 'somalia' 'south africa' 'south sudan' 'spain'
 'sri lanka' 'st. kitts and nevis' 'st. lucia' 'st. martin (french part)'
 'st. vincent and the grenadines' 'sudan' 'suriname' 'sweden'
 'switzerland' 'syria' 'tajikistan' 'tanzania' 'thailand' 'timor-leste'
 'togo' 'tonga' 'trinidad and tobago' 'tunisia' 'turkey' 'turkmenistan'
 'turks and caicos islands' 'tuvalu' 'uganda' 'ukraine'
 'united arab emirates' 'united kingdom' 'united states' 'uruguay'
 'uzbekistan' 'vanuatu' 'venezuela, rb' 'vietnam' 'virgin islands (u.s.)'
 'west bank and gaza' 'yemen' 'zambia' 'zimbabwe']

Rainfall Category:
          Area  average_rain_fall_mm_per_year Rainfall_Category
0  afghanistan                          359.7               Low
1  afghanistan                          359.7               Low
2  afghanistan                          359.7               Low
3  afghanistan                          359.7               Low
4  afghanistan                          359.7               Low

Areas with rainfall greater than 10:
             Area  Year  average_rain_fall_mm_per_year Rainfall_Category
0     afghanistan  1985                          359.7               Low
1     afghanistan  1986                          359.7               Low
2     afghanistan  1987                          359.7               Low
3     afghanistan  1989                          359.7               Low
4     afghanistan  1990                          359.7               Low
...           ...   ...                            ...               ...
6722     zimbabwe  2013                          722.7               Low
6723     zimbabwe  2014                          722.7               Low
6724     zimbabwe  2015                          722.7               Low
6725     zimbabwe  2016                          722.7               Low
6726     zimbabwe  2017                          722.7               Low

[6727 rows x 4 columns]

After dropping Year:
          Area  average_rain_fall_mm_per_year Rainfall_Category
0  afghanistan                          359.7               Low
1  afghanistan                          359.7               Low
2  afghanistan                          359.7               Low
3  afghanistan                          359.7               Low
4  afghanistan                          359.7               Low

After One-Hot Encoding:
   average_rain_fall_mm_per_year Rainfall_Category  Area_afghanistan  \
0                          359.7               Low              True
1                          359.7               Low              True
2                          359.7               Low              True
3                          359.7               Low              True
4                          359.7               Low              True

   Area_albania  Area_algeria  Area_american samoa  Area_andorra  Area_angola  \
0         False         False                False         False        False
1         False         False                False         False        False
2         False         False                False         False        False
3         False         False                False         False        False
4         False         False                False         False        False

   Area_antigua and barbuda  Area_argentina  ...  Area_uruguay  \
0                     False           False  ...         False
1                     False           False  ...         False
2                     False           False  ...         False
3                     False           False  ...         False
4                     False           False  ...         False

   Area_uzbekistan  Area_vanuatu  Area_venezuela, rb  Area_vietnam  \
0            False         False               False         False
1            False         False               False         False
2            False         False               False         False
3            False         False               False         False
4            False         False               False         False

   Area_virgin islands (u.s.)  Area_west bank and gaza  Area_yemen  \
0                       False                    False       False
1                       False                    False       False
2                       False                    False       False
3                       False                    False       False
4                       False                    False       False

   Area_zambia  Area_zimbabwe
0        False          False
1        False          False
2        False          False
3        False          False
4        False          False

[5 rows x 219 columns]

Sorted by rainfall (highest first):
      average_rain_fall_mm_per_year Rainfall_Category  Area_afghanistan  \
1322                         3564.0              High             False
1310                         3564.0              High             False
1311                         3564.0              High             False
1305                         3564.0              High             False
1307                         3564.0              High             False

      Area_albania  Area_algeria  Area_american samoa  Area_andorra  \
1322         False         False                False         False
1310         False         False                False         False
1311         False         False                False         False
1305         False         False                False         False
1307         False         False                False         False

      Area_angola  Area_antigua and barbuda  Area_argentina  ...  \
1322        False                     False           False  ...
1310        False                     False           False  ...
1311        False                     False           False  ...
1305        False                     False           False  ...
1307        False                     False           False  ...

      Area_uruguay  Area_uzbekistan  Area_vanuatu  Area_venezuela, rb  \
1322         False            False         False               False
1310         False            False         False               False
1311         False            False         False               False
1305         False            False         False               False
1307         False            False         False               False

      Area_vietnam  Area_virgin islands (u.s.)  Area_west bank and gaza  \
1322         False                       False                    False
1310         False                       False                    False
1311         False                       False                    False
1305         False                       False                    False
1307         False                       False                    False

      Area_yemen  Area_zambia  Area_zimbabwe
1322       False        False          False
1310       False        False          False
1311       False        False          False
1305       False        False          False
1307       False        False          False

[5 rows x 219 columns]